server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/prl
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  http:
    encoding:
      charset: UTF-8
      
  main:
    allow-bean-definition-overriding: true

uah:
  rabbitmq:
    exchange: uah.prl.exchange
    queue: uah.prl.queue
    routingkey: uah.prl.routingkey
